### ISSUE TITLE
Open wiki?

### ISSUE THREAD

**Issue by jmitchell** [mikepound/mazesolving#10]
Thank you for sharing this project and the video. I've had fun playing with it.

I noticed the recent addition to the README saying pull requests and issues generally aren't encouraged. Maintaining a project can be tedious, especially it's just a personal hobby project. I think it would be nice if people interested in the project could collaborate, even if you're not involved.

Would you consider [making the project's wiki public](https://help.github.com/articles/changing-access-permissions-for-wikis/) or suggesting in the README some other avenue for people interested in discussing ideas and sharing their forks?

**Comment by mikepound** [comment]
I have no problem with this. It's purely time constraints, realistically at some point I'll have to focus on other projects! I mainly left the readme note in case people spent a long time making things better, only to find their pull request was ignored because I wasn't paying attention.

I'm happy to make the wiki public (that should now be done). An alternative is I grant you and whoever access to a development branch and you can continue in there, and the master (or some other default) remains in its current state for people visiting from the video. The readme could point to another repo held elsewhere if that's easier.

**Comment by alecthegeek** [comment]
Just tag a commit and point people from the video at that.

Then appoint some project maintainers, in the same way as other open projects, to handle pull requests and other admin.

I'd offer myself, but I'm already over committed :-(

**Comment by jmitchell** [comment]
@mikepound, thank you. I started a page to document the forks and their enhancements [here](https://github.com/mikepound/mazesolving/wiki/Forks).

I empathize with the limited time issue, so I'm also not inclined to maintain an alternative branch. Perhaps if enough people make several orthogonal enhancements or start duplicating work and make it known on the forks page I'd reconsider.

I like @alecthegeek's idea of using a tag to denote the version corresponding to the video.
